from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import select

from trading_system.app.ai.decision_support import build_artifact_payload, get_decision_support_provider
from trading_system.app.db import models
from trading_system.app.db.repositories import TradingRepository


REVIEW_ENGINE_VERSION = "trade_review_v1"


@dataclass(frozen=True)
class ReviewRunResult:
    journal_entries_seen: int
    reviews_created: int
    reason: str
    version: str = REVIEW_ENGINE_VERSION


class TradeReviewEngine:
    def __init__(self, repository: TradingRepository) -> None:
        self.repository = repository

    def run_once(self) -> ReviewRunResult:
        journals = self.repository.session.scalars(select(models.TradeJournal).limit(500)).all()
        created = 0
        for journal in journals:
            existing = self.repository.session.scalar(
                select(models.AIReview).where(models.AIReview.trade_journal_id == journal.id)
            )
            if existing:
                continue
            review_payload = self._build_review_payload(journal)
            provider = get_decision_support_provider()
            review = provider.review_trade(review_payload)
            artifact = build_artifact_payload(
                artifact_type="TRADE_REVIEW",
                provider=provider,
                prompt_version=REVIEW_ENGINE_VERSION,
                input_payload=review_payload,
                output=review,
                fallback_used=True,
            )
            artifact_row = self.repository.store_decision_support_artifact(
                artifact,
                reason="Decision-support trade review generated for journal entry.",
                source_timestamp=journal.source_timestamp,
            )
            if not artifact.validation.accepted:
                continue
            review_text = self._review_text(artifact.output_payload)
            self.repository.store_ai_review(
                trade_journal_id=journal.id,
                prompt_version=REVIEW_ENGINE_VERSION,
                review_text=review_text,
                confidence_score=float(artifact.output_payload.get("confidence_score") or 70.0),
                decision_support_artifact_id=artifact_row.id,
                structured_payload=artifact.output_payload,
                reason="Decision-support review generated by deterministic provider; external AI not required.",
                source_timestamp=journal.source_timestamp,
            )
            journal.ai_review = review_text
            self.repository.session.commit()
            created += 1
        return ReviewRunResult(
            journal_entries_seen=len(journals),
            reviews_created=created,
            reason="Trade reviews generated for unreviewed journal entries.",
        )

    def _build_review_payload(self, journal: models.TradeJournal) -> dict:
        return {
            "journal_id": journal.id,
            "symbol": journal.symbol,
            "strategy_id": journal.strategy_id,
            "actual_entry": journal.actual_entry,
            "actual_exit": journal.actual_exit,
            "market_regime": journal.market_regime,
            "catalyst": journal.catalyst,
            "pnl": journal.pnl,
            "max_favorable_excursion": journal.max_favorable_excursion,
            "max_adverse_excursion": journal.max_adverse_excursion,
            "slippage_bps": journal.slippage_bps,
            "time_in_trade_seconds": journal.time_in_trade_seconds,
            "rule_violations": journal.rule_violations or [],
            "mistake_tags": journal.mistake_tags or [],
        }

    @staticmethod
    def _review_text(payload: dict) -> str:
        return (
            f"{payload['summary']} {payload['rule_adherence']} "
            f"{payload['slippage_assessment']} {payload['timing_assessment']} "
            f"Follow-up: {payload['follow_up_action']} {payload['disclaimer']}"
        )
