from __future__ import annotations

from trading_system.app.core.enums import ProviderReliabilityLevel, StrategyStatus, TradeType


DEFAULT_PROVIDER_CAPABILITIES = [
    {
        "provider_name": "alpaca_paper",
        "allowed_usage": "Paper execution and market data when credentials/subscription permit.",
        "rate_limit_notes": "Use broker/provider limits from current Alpaca account.",
        "reliability_level": ProviderReliabilityLevel.MEDIUM.value,
        "live_trading_allowed": False,
        "research_allowed": True,
        "intraday_allowed": True,
        "enrichment_allowed": False,
        "reason": "Paper trading is simulated and cannot prove live execution quality.",
    },
    {
        "provider_name": "alpaca_live",
        "allowed_usage": "Live broker execution only after every live-readiness and human approval gate passes.",
        "rate_limit_notes": "Use the current Alpaca account limits; live order retries are restricted to transient network failures.",
        "reliability_level": ProviderReliabilityLevel.HIGH.value,
        "live_trading_allowed": True,
        "research_allowed": False,
        "intraday_allowed": False,
        "enrichment_allowed": False,
        "reason": "Separate live execution adapter; disabled by default and never reused from paper config.",
    },
    {
        "provider_name": "alpaca_market_data",
        "allowed_usage": "Production market data stream via Alpaca websocket; feed depends on subscription.",
        "rate_limit_notes": "IEX is available on free market data; SIP requires the appropriate subscription.",
        "reliability_level": ProviderReliabilityLevel.HIGH.value,
        "live_trading_allowed": False,
        "research_allowed": True,
        "intraday_allowed": True,
        "enrichment_allowed": False,
        "reason": "Approved market-data provider; still not an execution authority.",
    },
    {
        "provider_name": "yfinance",
        "allowed_usage": "Research and prototyping only.",
        "rate_limit_notes": "Unofficial/free data source; not suitable for production execution.",
        "reliability_level": ProviderReliabilityLevel.LOW.value,
        "live_trading_allowed": False,
        "research_allowed": True,
        "intraday_allowed": False,
        "enrichment_allowed": True,
        "reason": "Research convenience source, not execution-grade market data.",
    },
    {
        "provider_name": "yahoo_chart",
        "allowed_usage": "Real Yahoo chart API data for research dashboard scans only.",
        "rate_limit_notes": "Unofficial public chart endpoint; do not use as execution-grade data.",
        "reliability_level": ProviderReliabilityLevel.LOW.value,
        "live_trading_allowed": False,
        "research_allowed": True,
        "intraday_allowed": True,
        "enrichment_allowed": True,
        "reason": "Functional no-key research fallback; not approved for live execution.",
    },
    {
        "provider_name": "alpha_vantage",
        "allowed_usage": "Enrichment only, not heavy intraday collection.",
        "rate_limit_notes": "Free tier is too limited for high-frequency collection.",
        "reliability_level": ProviderReliabilityLevel.MEDIUM.value,
        "live_trading_allowed": False,
        "research_allowed": True,
        "intraday_allowed": False,
        "enrichment_allowed": True,
        "reason": "Rate limits make it unsuitable as the main intraday source.",
    },
    {
        "provider_name": "sec_edgar",
        "allowed_usage": "Slow filings, XBRL, fundamentals, and catalyst context.",
        "rate_limit_notes": "Respect SEC fair-access behavior and identify requests.",
        "reliability_level": ProviderReliabilityLevel.HIGH.value,
        "live_trading_allowed": False,
        "research_allowed": True,
        "intraday_allowed": False,
        "enrichment_allowed": True,
        "reason": "Excellent context source, not day-trading execution data.",
    },
    {
        "provider_name": "news",
        "allowed_usage": "Catalyst enrichment, source confidence, and duplicate headline detection.",
        "rate_limit_notes": "Provider-specific.",
        "reliability_level": ProviderReliabilityLevel.MEDIUM.value,
        "live_trading_allowed": False,
        "research_allowed": True,
        "intraday_allowed": False,
        "enrichment_allowed": True,
        "reason": "News can inform thesis but cannot bypass risk controls.",
    },
]


DEFAULT_STRATEGIES = [
    {
        "strategy_id": "VWAP_RECLAIM",
        "name": "VWAP Reclaim",
        "version": "v1",
        "status": StrategyStatus.RESEARCH.value,
        "trade_type": TradeType.DAY_TRADE.value,
        "allowed_timeframes": ["1Min", "5Min"],
        "allowed_regimes": ["BULL_TREND", "RISK_ON", "CHOPPY"],
        "requires_human_approval": True,
        "logic_version": "v1",
        "changed_reason": "Initial research seed; paper/live status requires approval evidence.",
    },
    {
        "strategy_id": "POST_EARNINGS_CONTINUATION",
        "name": "Post-Earnings Continuation",
        "version": "v1",
        "status": StrategyStatus.RESEARCH.value,
        "trade_type": TradeType.SWING.value,
        "allowed_timeframes": ["1D"],
        "allowed_regimes": ["BULL_TREND", "RISK_ON"],
        "requires_human_approval": True,
        "logic_version": "v1",
        "changed_reason": "Seeded for paper testing after research validation.",
    },
    {
        "strategy_id": "OPENING_RANGE_BREAKOUT",
        "name": "Opening Range Breakout",
        "version": "v1",
        "status": StrategyStatus.RESEARCH.value,
        "trade_type": TradeType.DAY_TRADE.value,
        "allowed_timeframes": ["1Min", "5Min", "15Min"],
        "allowed_regimes": ["BULL_TREND", "RISK_ON"],
        "requires_human_approval": True,
        "logic_version": "v1",
        "changed_reason": "Production scanner seeded in research state.",
    },
    {
        "strategy_id": "NEWS_MOMENTUM",
        "name": "News Momentum",
        "version": "v1",
        "status": StrategyStatus.RESEARCH.value,
        "trade_type": TradeType.DAY_TRADE.value,
        "allowed_timeframes": ["1Min", "5Min"],
        "allowed_regimes": ["BULL_TREND", "RISK_ON", "CHOPPY"],
        "requires_human_approval": True,
        "logic_version": "v1",
        "changed_reason": "Production scanner seeded in research state.",
    },
    {
        "strategy_id": "CATALYST_RUN_UP",
        "name": "Catalyst Run-Up",
        "version": "v1",
        "status": StrategyStatus.RESEARCH.value,
        "trade_type": TradeType.QUARTER.value,
        "allowed_timeframes": ["1D"],
        "allowed_regimes": ["BULL_TREND", "RISK_ON"],
        "requires_human_approval": True,
        "logic_version": "v1",
        "changed_reason": "Production scanner seeded in research state.",
    },
    {
        "strategy_id": "RELATIVE_STRENGTH",
        "name": "Relative Strength",
        "version": "v1",
        "status": StrategyStatus.RESEARCH.value,
        "trade_type": TradeType.SWING.value,
        "allowed_timeframes": ["1D", "1Min"],
        "allowed_regimes": ["BULL_TREND", "RISK_ON"],
        "requires_human_approval": True,
        "logic_version": "v1",
        "changed_reason": "Production scanner seeded in research state.",
    },
    {
        "strategy_id": "SECTOR_LEADERSHIP",
        "name": "Sector Leadership",
        "version": "v1",
        "status": StrategyStatus.RESEARCH.value,
        "trade_type": TradeType.SWING.value,
        "allowed_timeframes": ["1D"],
        "allowed_regimes": ["BULL_TREND", "RISK_ON"],
        "requires_human_approval": True,
        "logic_version": "v1",
        "changed_reason": "Production scanner seeded in research state.",
    },
]


DEFAULT_SYMBOLS = [
    {
        "symbol": "SPY",
        "name": "SPDR S&P 500 ETF Trust",
        "asset_class": "US_EQUITY",
        "exchange": "NYSEARCA",
        "sector": "Index ETF",
        "industry": "ETF",
        "is_active": True,
        "change_reason": "Seeded liquid benchmark for market context.",
    },
    {
        "symbol": "QQQ",
        "name": "Invesco QQQ Trust",
        "asset_class": "US_EQUITY",
        "exchange": "NASDAQ",
        "sector": "Index ETF",
        "industry": "ETF",
        "is_active": True,
        "change_reason": "Seeded liquid benchmark for market context.",
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices, Inc.",
        "asset_class": "US_EQUITY",
        "exchange": "NASDAQ",
        "sector": "Technology",
        "industry": "Semiconductors",
        "is_active": True,
        "change_reason": "Seeded liquid semiconductor watchlist symbol.",
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "asset_class": "US_EQUITY",
        "exchange": "NASDAQ",
        "sector": "Technology",
        "industry": "Semiconductors",
        "is_active": True,
        "change_reason": "Seeded liquid semiconductor watchlist symbol.",
    },
    {
        "symbol": "TSLA",
        "name": "Tesla, Inc.",
        "asset_class": "US_EQUITY",
        "exchange": "NASDAQ",
        "sector": "Consumer Cyclical",
        "industry": "Auto Manufacturers",
        "is_active": True,
        "change_reason": "Seeded liquid momentum watchlist symbol.",
    },
]
